### ISSUE TITLE
Clean A1 code

### ISSUE THREAD

**Issue by HarperThurlow** [JackMcKill/CP3407-Project#11]
Need to make sure our A1 code has correct naming conventions and is generally clean before continuing.

- [x] Clean current code
- [x] Write some documentation that outlines our coding practices and naming conventions.

**Comment by JackMcGill** [comment]
@HarperThurlow Good issue, I've added 2 subtasks to your top comment. Looking at the assignment document, there is a section about onboarding new contributors to the project. 
I reckon we should create some documentation that outlines the onboarding process, and also explains some of our naming conventions and coding / management / contributing processes. Very much like what we had to do for the CMS subject. What do you reckon? 
Kinda in-line with #2, basically just making sure we write good documentation as we develop the project.

**Comment by HarperThurlow** [comment]
Yeah I agree. Good documentation will make it easy for Dimitry to read too because seeing a whole new heap of code can be overwhelming so having it set out and explaining variables/ naming conventions is a good idea. 
>making sure we write good documentation as we develop the project.

100% to this. Let's try to keep documentation up as we go along so we don't have to remember backwards as we go.
