### ISSUE TITLE
Split external database code

### ISSUE THREAD

**Issue by HarperThurlow** [JackMcKill/CP3407-Project#12]
Current external database code has 1 function. We need to split this into 3 different functions.

- [x] Connect to database
- [x] Read the database
- [ ] Write to the database

**Comment by HarperThurlow** [comment]
Current issue blocked for 2 reasons.
1. Internet at home is currently down causing issues working on connecting and reading to the database (phone data fully used trying to work with this).
2. async task difficult to work with and trying to work on different classes talking to each other. With help from @JackMcKill this task can move forward a little more however still having issues getting them to talk to each other properly.

**Comment by JackMcGill** [comment]
All good, we can revisit this later. Will probably be beneficial to take a break and come at it with a fresh perspective after working on something else for a little bit.
