### ISSUE TITLE
Settings: Display

### ISSUE THREAD

**Issue by calebwebster** [JackMcKill/CP3407-Project#18]
The weather app requires various display settings to allow users to customize their experience with the app. These should be located in the settings page.

***Display Settings***
- [ ] Setting to change font size for accessibility
- [ ] Toggle button to change between Imperial and Metric measurements

**Comment by JackMcGill** [comment]
@CalebWebsterJCU I didn't notice that you had assigned yourself to this before I pushed my changes up in 08d4142. If you have started working on this however, create a PR anyway so we can compare, I'm keen to see what you've come up, with as my implementation is very boring.
