### ISSUE TITLE
Improve README

### ISSUE THREAD

**Issue by JackMcGill** [JackMcKill/CP3407-Project#2]
Our README should contain:

* Brief description of our app
* Description of the project itself 
* Dependancies & API's used
* Contributors

**Comment by daniellekush** [comment]
Hey, I'd love to help out with this if possible.

**Comment by JackMcGill** [comment]
> Hey, I'd love to help out with this if possible.  

Thanks for the offer @daniellekush, but this is actually a University assessment item and I completely forgot to set the repo to private. As it's assessed, the only contributions can be from our internal project group unfortunately. I will be changing the repo's status to private after this comment, but feel free to check-in again in December after it has been submitted and marked! 
Happy coding.
