### ISSUE TITLE
API Activity Data Presentation

### ISSUE THREAD

**Issue by calebwebster** [JackMcKill/CP3407-Project#39]
## Overview

Currently, our API displays city weather data like this:

![Old API Activity](https://user-images.githubusercontent.com/61309806/136876971-9582f413-9c36-44f5-8cb3-99c9a9fe050f.png)

We want a more stylised look and feel that presents only the necessary data.

- [x] Create new ArrayAdapter to allow ConstraintLayouts to be used in ListView
- [x] Create new xml layout for the ListView WeatherReportModel items
- [x] Perform data insertion
- [x] Change weather state images

**Comment by JackMcGill** [comment]
@CalebWebsterJCU can I also request that the `APIactivity` name and its related layout file name be refactored to something more suitable, such as `SearchActivity` or something similar? `APIactivity` was just the name I gave to prototype the API calls, but we ended up sticking with the OG file.
