### ISSUE TITLE
Homescreen GUI

### ISSUE THREAD

**Issue by JackMcGill** [JackMcKill/CP3407-Project#4]
## Old issue
~~A simple home screen GUI to prototype.~~

## New issue
Moving beyond the prototyping stage now. 
Our Home Screen should try and look similar to this:
![Screen Shot 2021-09-17 at 10 50 29 am](https://user-images.githubusercontent.com/14053993/133706582-7568adb9-eba4-4281-8671-af962fc5eddd.png).

### The basic elements of the layout
The layout should contain:
> You can tick these off as you complete them. 
- [x] A large `TextView` at the top displaying the "Today's Weather" title
- [x] A smaller `TextView` underneath that displays the current day
- [x] An `EditText` that can be used to search for a new location (this can be recycled from the `activity_apiactivity.xml` layout file.
- [x] A `ListView` underneath showing the favourite locations
- [x] A text `Button` underneath the list to edit the favourite locations
- [x] Another `Button` to take the user to the Apps settings page.

The scope of this issue is _just the layout_ - the actual code behind the scenes to make the elements dynamic (like the current day displaying, and the favourite locations populating the list) is **outside** the scope of this issue.

**Comment by HarperThurlow** [comment]
This can be extended for all screens for GUI. Will talk about in next meeting and can start creating a list of each screen :)

**Comment by JackMcGill** [comment]
I've updated this issues description - we can use that as a template for the other GUI screens.
