### ISSUE TITLE
Database

### ISSUE THREAD

**Issue by JackMcGill** [JackMcKill/CP3407-Project#5]
We need an externally hosted database, so we will need some code to connect to it, and demonstrate read and write capabilities.

## ToDo:

- [x] Local database
- [x] External database

**Comment by HarperThurlow** [comment]
After some research I am going to try getting an Amazon RDS instance to talk to Android Studio. This may not be the final decision but if I can get these two to communicate with each other it will set us on the right track for a prototype.

**Comment by JackMcGill** [comment]
Sounds like a great plan to me. So long as we can get some 2-way talking going on it'll fit the Assignment 1 requirements.

**Comment by HarperThurlow** [comment]
Have managed to get the external database set up on Thursday and currently having issues connecting them through Java.
Tested through Python (as a baseline) and can sucessfully connect to the external database and manipulate/view data from there (so we know its not the backend of the database). Attempting to find the fix through debugging and online sources friday & saturday

**Comment by JackMcGill** [comment]
@HarperThurlow Awesome work with getting the database talking to the app successfully, one step closer to finishing off this prototype. I think we should remove the final task in this issue of implementing an interface between the 2 databases, as it's beyond the scope of Assignment 1. We can make it its own issue to be worked on later on, and for now we can focus on polishing off what we have to give to Dimitri. What do you think?

**Comment by HarperThurlow** [comment]
Yep I agree. Proj 1 seems like it's more focused on just getting the external database talking to the app. Feel free to close this tread when you are ready 👍
